[package]
name = "another-cyclic-datastructure"
version = "0.1.0"
authors = ["Ivan Dubrov <dubrov.ivan@gmail.com>"]

[dependencies]
serde = "1.0.66"
serde_derive = "1.0.66"
serde_json = { version = "1.0.19", features = ["preserve_order"] }
indexmap = { version = "1.0.1", features = ["serde-1"] }